### ISSUE TITLE
Sync after restart is slow

### ISSUE THREAD

**Issue by rolanddb** [energywebfoundation/authority-node#1]
I rebooted the VM that hosts our authority node (for testing purposes, just to see if everything will start up correctly).

The authority node starts up, but syncing the import is very slow. The reported size of the chain is now 2MB where before rebooting, it was 5MB.
I monitored the webpage with netstats for a while. It looks like the node is not really catching up with the rest of the network.

I am new to blockchains and only have a highlevel understanding of how it all works. But it seems that there are some options to speed up the syncing, such as --warp: https://blog.ethcore.io/announcing-parity-1-4/

Also this stackoverflow post has some information about tuning:
https://ethereum.stackexchange.com/questions/10465/is-it-possible-to-make-the-parity-software-sync-faster#10470

The VM shows a load avg of about 0.45 (reported by top) and 6 out of 8gb memory is free. Can we somehow utilize more of the VM's resources? Nothing else besides the authority node runs on this VM.

**Comment by jbentke** [comment]
Your node forked, thats why it seems like its synching slowly. It produces blocks at his turn which will be rejected on the main chain but accepted on you chain. Your node is progressing 1/n speed then the main net, where n is the number of authority nodes. 

There are some indicators on netstats which you can use to see if a fork happened. First, the block time is double the length at one point. That means one block didn't get produced in time. Second is obviously the blocknumber. Another one, also not always clear to see is the number of peers. You can see that more clearly when running a client on you local computer and try to add your node as a reserved peer (in the status page). You see that it will connect and then straight away drop it again. It will pop on and off again.

Looking at the logs you send me, the fork happened when I rebootet the nodes. For some reason the eneco node missed that update and stayed online. Then it reported ```WARN client  Stage 3 block verification failed for #1189271 (6af7…3278) Error: Block(TooManyUncles(OutOfBounds { min: None, max: Some(0), found: 1 }))``` which caused the node to fork. 

I reported the issue to parity so they can have a look on why this happened and how to fix it.

**Comment by rolanddb** [comment]
Thanks, your analysis is correct. After reparing the fork, restarts are not an issue anymore, our node rejoins the network almost instantaneously.
